FROM quay.io/keycloak/keycloak:latest

ENV KC_HOME /opt/keycloak
ENV KC_IMPORT_DIR ${KC_HOME}/data/import

COPY product-realm.json ${KC_IMPORT_DIR}/

ENV KC_DB=postgres
ENV KC_DB_URL=jdbc:postgresql://product-db:5432/keycloakdb
ENV KC_DB_USERNAME=keycloak_user
ENV KC_DB_PASSWORD=password

ENV KEYCLOAK_ADMIN=keycloak
ENV KEYCLOAK_ADMIN_PASSWORD=keycloak

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--optimized", "--import-realm", "--auto-build"]
