spring:
  application:
    name: product-api
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

springdoc:
  api-docs:
    enabled: true

server:
  port: 7777
  error:
    include-message: on_param

logging:
  level:
    org:
      springframework:
        security: TRACE

external:
  hnb:
    refresh:
      cron: 0 0 6 * * *
    api:
      url: https://api.hnb.hr/tecajn-eur/v3