spring:
  application:
    name: product-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/idm
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  jackson:
    default-property-inclusion: non_null

springdoc:
  api-docs:
    enabled: true

server:
  port: 7777
  error:
    include-message: always

logging:
  level:
    org:
      springframework:
        security: TRACE

external:
  hnb:
    refresh:
      cron: 0 0 6 * * *
    api:
      url: https://api.hnb.hr/tecajn-eur/v3